version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    command: sleep infinity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
